# Generated by Django 5.2.8 on 2026-01-08 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='app.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_news', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved News',
                'verbose_name_plural': 'Saved News List',
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'news')},
            },
        ),
    ]
